services:
  jekyll:
    image: jekyll/jekyll:4
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: bash -c "cd /srv/jekyll && bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload"
    environment:
      - JEKYLL_ENV=development
